runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth2=depth2" >>$GITHUB_OUTPUT
  - uses: redgarb/local-post-step-bug/depth3-absolut@main
    id: depth2
  - uses: redgarb/local-post-steps-bug/post-step@main
    with:
      STEPS: ${{ tojson(steps) }}
