outputs:
  depth2:
    description: "Bla, bla, blub."
    value: ${{ steps.output-value.outputs.depth2 }}
  depth3:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth3 }}
  depth4:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth4 }}

runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth2=depth2" >>$GITHUB_OUTPUT
  - uses: redgarb/local-post-steps-bug/.github/actions/depth3-absolut@master
    id: depth
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth2 -> ${{ steps.output-value.outputs.depth2 }}"
      echo "Should be depth3 -> ${{ steps.depth.outputs.depth3 }}"
      echo "Should be depth4 -> ${{ steps.depth.outputs.depth4 }}"
  - uses: redgarb/local-post-steps-bug/.github/actions/post-step@master
    with:
      STEPS: ${{ tojson(steps) }}
