runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth3=depth3" >>$GITHUB_OUTPUT
      echo "depth3=depth3" >>$GITHUB_ENV
  - uses: redgarb/local-post-steps-bug/.github/workflow/actions/depth4-absolut@master
    id: depth3
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth3 -> ${{ steps.output-value.outputs.depth3 }}"
      echo "Should be depth3 -> ${{ env.depth3 }}"
      echo "Should be depth4 -> ${{ steps.depth2.outputs.depth4 }}"
      echo "Should be depth4 -> ${{ env.depth4 }}"
  - uses: redgarb/local-post-steps-bug/.github/workflow/actions/post-step@master
    with:
      STEPS: ${{ tojson(steps) }}
