outputs:
  depth3:
    description: "Bla, bla, blub."
    value: ${{ steps.output-value.outputs.depth3 }}
  depth4:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth4 }}

runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth3=depth3" >>$GITHUB_OUTPUT
  - uses: .github/actions/relative/depth4
    id: depth
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth3 -> ${{ steps.output-value.outputs.depth3 }}"
      echo "Should be depth4 -> ${{ steps.depth.outputs.depth4 }}"
  - uses: .github/actions/post-step
    with:
      STEPS: ${{ tojson(steps) }}
