outputs:
  depth1:
    description: "Bla, bla, blub."
    value: ${{ steps.output-value.outputs.depth1 }}
  depth2:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth2 }}
  depth3:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth3 }}
  depth4:
    description: "Bla, bla, blub."
    value: ${{ steps.depth.outputs.depth4 }}

runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth1=depth1" >>$GITHUB_OUTPUT
  - uses: .github/actions/relative/depth2
    id: depth
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth1 -> ${{ steps.output-value.outputs.depth1 }}"
      echo "Should be depth2 -> ${{ steps.depth.outputs.depth2 }}"
      echo "Should be depth3 -> ${{ steps.depth.outputs.depth3 }}"
      echo "Should be depth4 -> ${{ steps.depth.outputs.depth4 }}"
  - uses: .github/actions/post-step
    with:
      STEPS: ${{ tojson(steps) }}
