runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth4=depth4" >>$GITHUB_OUTPUT
      echo "depth4=depth4" >>$GITHUB_ENV
  - uses: ./.github/actions/post-step
    with:
      STEPS: ${{ tojson(steps) }}
