runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth4=depth4" >>$GITHUB_OUTPUT
  - uses: redgarb/local-post-steps-bug/post-step@main
    with:
      STEPS: ${{ tojson(steps) }}
