runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth4=depth4" >>$GITHUB_OUTPUT
  - id: debug-outputs
    shell: bash
    run: |
      echo "Should be depth4 -> ${{ steps.output-value.outputs.depth1 }}
  - uses: redgarb/local-post-steps-bug/post-step@master
    with:
      STEPS: ${{ tojson(steps) }}
