runs:
  using: composite
  steps:
  - id: output-value
    shell: bash
    run: |
      echo "depth1=depth1" >>$GITHUB_OUTPUT
      echo "depth1=depth1" >>$GITHUB_ENV
  - uses: ./depth2
    id: depth2
  - uses: ./.github/workflows/actions/post-step
    with:
      STEPS: ${{ tojson(steps) }}
